# Generated by Django 3.1.7 on 2021-03-25 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plane_messages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='column',
            new_name='detail',
        ),
        migrations.AddField(
            model_name='message',
            name='number',
            field=models.IntegerField(null=True),
        ),
    ]
