# Generated by Django 3.1.7 on 2021-03-25 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plane_messages', '0002_auto_20210325_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='detail',
        ),
        migrations.AddField(
            model_name='message',
            name='details',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='title',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
