# Generated by Django 3.1.7 on 2021-03-25 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plane_messages', '0004_auto_20210325_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='title',
            field=models.CharField(max_length=120),
        ),
    ]
