# Generated by Django 3.1.7 on 2021-03-30 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plane_messages', '0005_auto_20210325_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='id',
        ),
        migrations.AddField(
            model_name='message',
            name='message_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
