# Generated by Django 3.1.7 on 2021-03-25 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plane',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column', models.CharField(max_length=120)),
                ('value', models.TextField()),
                ('plane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='plane_messages.plane')),
            ],
        ),
    ]
